### PR TITLE
Correct developer_name metadata

### PR DESCRIPTION
**Pull request by ghisvail**

### CODE REVIEW

**Comment by proletarius101** [comment]
It's requested by the upstream: https://github.com/flathub/org.standardnotes.standardnotes/pull/3

**Comment by ghisvail** [comment]
I think upstream did not read what this tag is about in the [appstream spec](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html) :

```
<developer_name/> #

    The <developer_name/> tag is designed to represent the developers or project responsible for development of the project described in the metadata.

    Values might be for example "The GNOME Foundation" or "The KDE Community". You must not include hyperlinks or emails in this field, if you want to link to the developer's homepage, use the <url/>-tag instead.

    This tag is translatable. 
```

**Comment by ghisvail** [comment]
There is also a `contact` tag which should probably be set to yourself.

**Comment by mobitar** [comment]
I don't know, how would you feel if you downloaded, for example, Signal Messenger from Flathub thinking it was packaged by the official Signal Foundation, only to find out it was actually built, compiled, and released by some totally unaffiliated party? Would Edward Snowden download such a package? I don't think so. Takes away a large part of the premise. We simply can't have our name on a software distributable we did not create. This is a very dangerous precedent. 

The best solution is that we create our own releases for Flathub so that they come from a trusted source, but until we have the bandwidth for that, we owe users downloading this package the transparency to see it's not coming from us. I would honestly prefer it in the title, but this is also good enough. As for me, clearly seeing this information would change whether or not I download this package. Making this information harder to see will likely result in more participation, but for the wrong reasons.

**Comment by proletarius101** [comment]
Hmm, I agree that we need transparency. But how is this done usually? I believe most packages on flathub is not directly owned by the upstream maintainer. So as most linux packages. The considerations are shared.

**Comment by ghisvail** [comment]
Whether we're working on a Flatpak or DEB package, we are merely `distributing` some upstream software in some shape or form. There is no development involved in the traditional sense, beyond maintaining a set of scripts and integration patches. 

Whether Flatpak packaging is `owned` or `supported` by upstream does not change what the metadata of the upstream software being packaged are. The `developer_name` as intended in the AppStream spec should really be upstream's. The contact links for support however should point to whatever upstream seems more comfortable with, whether it's themselves or the downstream packager. Hence my suggestion to update the contact information accordingly instead.

**Comment by Erick555** [comment]
> I don't know, how would you feel if you downloaded, for example, Signal Messenger from Flathub thinking it was packaged by the official Signal Foundation, only to find out it was actually built, compiled, and released by some totally unaffiliated party?

The thing is nothing states this app was packaged/published/maintained by upstream. If you go to the app page you see that _Developer_ and _Publisher_ are separate fields and the second one doesn't point to upstream. Actually there is a signal on flathub which just copy the binaries uploaded from signal site but hasn't any affiliation with signal developers. [It lists signal foundation as developer](https://github.com/flathub/org.signal.Signal/blob/master/org.signal.Signal.appdata.xml#L6).

> We simply can't have our name on a software distributable we did not create

Do you imply the software author is the one who send code into compiler instead of the one who wrote the code?

This problem [popped up before](https://github.com/flathub/im.riot.Riot/issues/87#issuecomment-638330638) and the conclusion was that Developer field means actual developer/author, not the flathub packager.

**Comment by mobitar** [comment]
Signal listing has this in it:

>  This flatpak is maintained by the Flathub community, and is not necessarily endorsed or officially maintained by the upstream developers.

It sounds like this is a common enough scenario to warrant its own metadata field. `is_non_affiliated` or similar. Otherwise a bunch of different packages will all try to say the same thing in a hundred different ways. Perhaps official packages should have a blue verified checkmark while non-official don't? Snapstore does this.

**Comment by proletarius101** [comment]
> Signal listing has this in it:

And standardnotes has this:

> NOTE: This release is not verified by, affiliated with, or supported by Standard Notes Ltd.

**Comment by mobitar** [comment]
Right, my point is that this is not transparent enough. Reading app store descriptions is as quaint as reading a terms of service.

**Comment by proletarius101** [comment]
> Right, my point is that this is not transparent enough. Reading app store descriptions is as quaint as reading a terms of service.

I think if you read who the developer is (and the publisher field at the right of it), you will notice this warning? Also, I don't see why anyone would find the dev but ignore the publisher on the right, as the latter is even highlighted.
Besides, there is even an

> (Unofficial) A simple and private place for your notes, thoughts, and life's work

right above the "Install" button

**Comment by proletarius101** [comment]
And actually I find a better reason for using the upstream author name: all apps, including those properatery, are processed by the flathub build server. That's a basic assumption of any apps.

The only flaw could be me changing the build script before anyone realize, which also applies to any apps. There are always non-upstream actors having access to the repo, although the main branch doesn't allow force-push so every change is logged.

**Comment by proletarius101** [comment]
So I decide to go with the convention, given that the "publisher" is clearly not StandardNotes Ltd., and the 2 disclaimers in the summary and the description.

**Pull request merged**
